@startuml

cloud "Infrastructure" as infrastructure1 {
    portin chat_port
    [OllamaServer] -> chat_port
}

interface "CLI-Chat" as SmartChat

component "LLMChat" {
    [LLMChat] -> chat_port
    [LLMChat] - SmartChat
}


actor user
SmartChat <- user : Provide code snippet


interface "mcp" as mcp_api
interface "api" as rest_api

[LLMChat] ..> () mcp_api: sse/stdio


component "Smart Compiler" {
    interface "use" as tools_api
    interface "use" as tools_mcp
    [REST API] - rest_api
    [MCP API] - mcp_api
    [Tools] - tools_api
    [MCP API] ..> tools_mcp
    [REST API] ..> tools_api
    tools_mcp -[Tools]
}

cloud "Infrastructure" as infrastructure2 {
    rest_api <.. [ExternalSystem] 
}

@enduml